### ISSUE TITLE
valgrind memcheck Illegal instruction when use nlohmann::json::parse

### ISSUE THREAD

**Issue by aixi** [nlohmann/json#2518]
I am write a program use  nlohmann::json, I found that my program may have memory leak, So I use valgrind to detect
memroy leak.But valgrind crashed because of illegal instructions

#### What is the issue you have?

Program terminated with signal SIGILL, Illegal instruction.

the following is valgrind core back trace

```
#0  0x000000000535cd51 in nlohmann::detail::lexer<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> > >::lexer (this=0x1ffeffe9b8, adapter=..., ignore_comments_=false) at /home/admin/nereus/nereus/third_party/nlohmann/json.hpp:5997
5997          , decimal_point_char(static_cast<char_int_type>(get_decimal_point()))
[Current thread is 1 (LWP 32106)]
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-23.el7.x86_64 expat-2.1.0-12.el7.x86_64 fontconfig-2.13.0-4.3.el7.x86_64 freetype-2.8-14.el7_9.1.x86_64 fribidi-1.0.2-1.el7_7.1.x86_64 glibc-2.17-317.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libgcc-4.8.5-44.el7.x86_64 libidn-1.28-4.el7.x86_64 libpng-1.5.13-8.el7.x86_64 libselinux-2.5-15.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libuuid-2.23.2-65.el7.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-3.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.44-22.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt
#0  0x000000000535cd51 in nlohmann::detail::lexer<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> > >::lexer (this=0x1ffeffe9b8, adapter=..., ignore_comments_=false) at /home/admin/nereus/nereus/third_party/nlohmann/json.hpp:5997
#1  0x000000000534d653 in nlohmann::detail::parser<nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> > >::parser(nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> >&&, std::function<bool (int, nlohmann::detail::parse_event_t, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&)>, bool, bool) (this=0x1ffeffe990, adapter=..., cb=...,
    allow_exceptions_=true, skip_comments=false) at /home/admin/nereus/nereus/third_party/nlohmann/json.hpp:10180
#2  0x00000000053422f9 in nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::parser<nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> > >(nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<char const*, std::string> >, std::function<bool (int, nlohmann::detail::parse_event_t, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&)>, bool, bool) (adapter=..., cb=..., allow_exceptions=true, ignore_comments=false)
    at /home/admin/nereus/nereus/third_party/nlohmann/json.hpp:16692
```

#### Please describe the steps to reproduce the issue.

1. wirte a program use nlohmann::json::parse, compile 
2. valgrind --tool=memcheck --leak-check=full --log-file=valgrind.log ./a.out
3.

#### Which compiler and operating system are you using?

- Compiler: gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
- Operating system: centos7 in a docker

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [x] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
Can you share the program you executed?

**Comment by aixi** [comment]
> Can you share the program you executed?

The program belongs to my company, maybe I can provide you with a program that can reproduce the valgrind bugs and remove other sensitive information, but it will take some time

**Comment by SteveGremory** [comment]
i'm facing the same issue now, was this resolved by any chance?

**Comment by nlohmann** [comment]
No, because no code was shared. We run Valgrind and MSAN in the CI, so I doubt there is a memory issue.
